### PR TITLE
Fitting and evaluation of dielectric properties

### PR DESCRIPTION
**Pull request by davkovacs**
This PR implements the functionality to reproduce https://pubs.rsc.org/en/content/articlehtml/2023/fd/d3fd00113j 

It needs some clean-up though.

### CODE REVIEW

**Comment by venkatkapil24** [comment]
@ilyes319 do you have a "dealine" until when you want this merged?

**Comment by ilyes319** [comment]
> @ilyes319 do you have a "dealine" until when you want this merged?

The priority  is to merge the multi-gpu and then this one.

**Comment by venkatkapil24** [comment]
can you give me a sense of time, as I will be on holiday (for a few weeks) at some point.

**Comment by venkatkapil24** [comment]
mainly clean up.

**Comment by davkovacs** [comment]
Maybe it would be best for me to clean this up, and Venkat and Ilyes you can review?

**Comment by alinelena** [comment]
this one will be good to be in main, especially since paper is up...

**Comment by venkatkapil24** [comment]
This can be closed as we have a new mu alpha branch. The hope is to have the new mu_alpha branch in main in a few weeks.

**Pull request closed without merging**
