### PR TITLE
Added a way to extract invariant node embeddings

### PR DESCRIPTION
**Pull request by RokasEl**
[Related issue](https://github.com/ACEsuit/mace/issues/68)

Added a method `get_node_invariant_descriptors` to extract the invariant part of the learnt node representations using MACE and models that inherit the MACE class.

Cleaned up the forward by putting the calculation of initial embeddings in a separate function.

Added tests for the descriptor retrieval.

Cleaned up test_models.py by adding fixtures to reduce code repetition.

### CODE REVIEW

**Comment by ilyes319** [comment]
Looks great, for sure we need to add a readme part for that at least.

**Comment by davkovacs** [comment]
We could have a function initialising a model with random weights and normalisation giving features on the same scale for all body-orders? And the user would just need to specify the model config and the chemical elements? 

This is a slightly different use-case from extracting the features from a trained model.

**Comment by ilyes319** [comment]
The average number of neighbours would make a global rescaling. If you want to make all the body order on the same scale, you must rescale them individually. The average number of neighbours would be enough to guarantee none is too small.

**Comment by gabor1** [comment]
> Looks great!
> 
> One thing to consider adding is an API for using it with a trained model. I am thinking about a thin wrapper class which takes a trained MACE model and returns an object that takes as input ase Atoms objects and returns the invariant features, perhaps in the arrays field of the Atoms object itself.
> 
> @gabor1 What do you think? How would the API be the most useful?

yes I think that would be very useful. it would be great to supply a "basic" descriptor trained on something big (at least element-diversity wise)

**Comment by RokasEl** [comment]
Added `get_invariant_descriptors` method to the `MACECalculator` which allows to directly extract the features from an atoms object.

Also added more tests the calculator, feature extraction block, and the function itself attached onto the MACE class.

**Comment by ilyes319** [comment]
@RokasEl I will be closing as implemented in the PR 0a74b7acd3680777c3ac1d8da4288160a386679d. Made a simpler and more general version.

**Pull request closed without merging**
