### PR TITLE
Update utils.py

### PR DESCRIPTION
**Pull request by sandipde**
at present the code crash if it contains a atoms with len 1 but without config_type key in info. Proposinf Fix  by introducing try: except.

### CODE REVIEW

**Comment by ilyes319** [comment]
Looks good to me, we should probably add a warning when we do the expect. Something like "Isolated atom found with no config type, assuming isolated atom". Maybe there is a case for the expect to return False also and assume that the true isolated atom are only with the proposer config_type.

**Comment by sandipde** [comment]
I was first confused but then realised It was a typo when I made the edit on web. Thanks for checking. I have updated the commit. Let me know if the proposal makes sense.

**Comment by ilyes319** [comment]
That is why it defaults to false, check the updated code

**Comment by gabor1** [comment]
In GAP, we pick up an “isolated atom” if it is (i) by itself in the structure, and (ii) the cell is larger than the receptive field, i.e. a sphere with the radius of the receptive field fits into the cell.


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

On 29 Mar 2023, at 13:46, davkovacs ***@***.***> wrote:



What if I have a primitive cell? That should not be treated as isolated atom, I think that's why it was like that.

**Pull request merged**
